version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=abc123.,
      - MSSQL_DATABASE=PINI
    ports:
      - "1433:1433" 
