version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      - MSSQL_SA_PASSWORD=abc123.,
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433" # Porta 1433 do contêiner mapeada para a porta 1433 do host (localhost)
